# Generated by Django 3.2.8 on 2022-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lastpos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postype', models.IntegerField(default=999)),
                ('lastposition', models.IntegerField(default=0)),
                ('createTime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='qqinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('userbackup', models.CharField(max_length=1000)),
                ('qqnumber', models.CharField(max_length=500)),
                ('keywordlist', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=2000)),
                ('createTime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tiebaads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webaddr', models.CharField(max_length=500)),
                ('keywordlist', models.CharField(max_length=1000)),
                ('createTime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tiebainfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('userbackup', models.CharField(max_length=1000)),
                ('webaddr', models.CharField(max_length=500)),
                ('keywordlist', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=2000)),
                ('createTime', models.DateField(auto_now=True)),
            ],
        ),
    ]
