# Generated by Django 3.2.8 on 2022-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpos',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qqinfo',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tiebaads',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tiebainfo',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
