# Generated by Django 3.2.8 on 2022-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220320_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiebaads',
            name='detail',
            field=models.CharField(default='hello', max_length=2000),
            preserve_default=False,
        ),
    ]
