# Generated by Django 3.2.8 on 2022-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_tiebaads_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lastpos',
            name='userid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
