# Generated by Django 3.2.8 on 2022-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20220326_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='usertype',
            field=models.IntegerField(default=0),
        ),
    ]
